// Code generated by sqlc. DO NOT EDIT.
// source: account.sql

package db

import (
	"context"
)

const createAccounts = `-- name: CreateAccounts :one
INSERT INTO accounts (
  name,
  email,
  password
)
VALUES (
  $1,
  $2,
  $3
)
RETURNING id
`

type CreateAccountsParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateAccounts(ctx context.Context, arg CreateAccountsParams) (int32, error) {
	row := q.db.QueryRow(ctx, createAccounts, arg.Name, arg.Email, arg.Password)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const selectAccounts = `-- name: SelectAccounts :one
SELECT id, name, email, password 
FROM accounts
WHERE email = $1
`

func (q *Queries) SelectAccounts(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, selectAccounts, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return i, err
}
