version: '3.5'

services:

  db:
    image: postgres
    restart: always
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=sa
        - POSTGRES_PASSWORD=zcommerce
        - POSTGRES_DB=commerce
        - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres  

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: zeihanaulia@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

  order:
    build:
      context: .
      dockerfile: "./deployments/docker/order/Dockerfile"
    restart: always
    command: order-rest
    environment: 
        - DB_MASTER_DSN=pgsql:host=db;port=5432;dbname=commerce;user=sa;password=zcommerce
        - DB_REPLICA_DSN=pgsql:host=db;port=5432;dbname=commerce;user=sa;password=zcommerce
    depends_on:
      - db
    ports: 
        - "8002:8002"
        # - "7070:7070" # metrics

  payment:
    build:
      context: .
      dockerfile: "./deployments/docker/payment/Dockerfile"
    restart: always
    command: payment-rest
    environment: 
        - DB_MASTER_DSN=pgsql:host=db;port=5432;dbname=commerce;user=sa;password=zcommerce
        - DB_REPLICA_DSN=pgsql:host=db;port=5432;dbname=commerce;user=sa;password=zcommerce
    depends_on:
      - db
    ports: 
        - "8003:8003"
        # - "7070:7070" # metrics

  account:
    build:
      context: .
      dockerfile: "./deployments/docker/account/Dockerfile"
    restart: always
    command: account-rest
    environment: 
        - DB_MASTER_DSN=pgsql:host=db;port=5432;dbname=commerce;user=sa;password=zcommerce
        - DB_REPLICA_DSN=pgsql:host=db;port=5432;dbname=commerce;user=sa;password=zcommerce
    depends_on:
      - db
    ports: 
        - "8004:8004"
        # - "7070:7070" # metrics

volumes:
    postgres:
    pgadmin: