// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"github.com/jackc/pgtype"
)

type Payment struct {
	ID             int32          `json:"id"`
	TrxID          string         `json:"trx_id"`
	ReferenceTrxID string         `json:"reference_trx_id"`
	Types          string         `json:"types"`
	FinalAmount    pgtype.Numeric `json:"final_amount"`
	Payloads       pgtype.JSON    `json:"payloads"`
	Status         string         `json:"status"`
}
