// Code generated by sqlc. DO NOT EDIT.
// source: payment.sql

package db

import (
	"context"

	"github.com/jackc/pgtype"
)

const registerPayments = `-- name: RegisterPayments :one
INSERT INTO payments (
  trx_id,
  reference_trx_id,
  types,
  final_amount,
  payloads,
  status
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id
`

type RegisterPaymentsParams struct {
	TrxID          string         `json:"trx_id"`
	ReferenceTrxID string         `json:"reference_trx_id"`
	Types          string         `json:"types"`
	FinalAmount    pgtype.Numeric `json:"final_amount"`
	Payload        pgtype.JSON    `json:"payload"`
	Status         string         `json:"status"`
}

func (q *Queries) RegisterPayments(ctx context.Context, arg RegisterPaymentsParams) (int32, error) {
	row := q.db.QueryRow(ctx, registerPayments,
		arg.TrxID,
		arg.ReferenceTrxID,
		arg.Types,
		arg.FinalAmount,
		arg.Payload,
		arg.Status,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
