// Code generated by sqlc. DO NOT EDIT.
// source: order.sql

package db

import (
	"context"

	"github.com/jackc/pgtype"
)

const ordersTask = `-- name: OrdersTask :one
INSERT INTO orders (
  trx_id,
  payment_trx_id,
  lock_items,
  status,
  customer_name,
  customer_address
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id
`

type OrdersTaskParams struct {
	TrxID           string      `json:"trx_id"`
	PaymentTrxID    string      `json:"payment_trx_id"`
	LockItems       pgtype.JSON `json:"lock_items"`
	Status          string      `json:"status"`
	CustomerName    string      `json:"customer_name"`
	CustomerAddress string      `json:"customer_address"`
}

func (q *Queries) OrdersTask(ctx context.Context, arg OrdersTaskParams) (int32, error) {
	row := q.db.QueryRow(ctx, ordersTask,
		arg.TrxID,
		arg.PaymentTrxID,
		arg.LockItems,
		arg.Status,
		arg.CustomerName,
		arg.CustomerAddress,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
